### ISSUE TITLE
papermap fails if `arial.ttf` cannot be found

### ISSUE THREAD

**Issue by flopp** [sgraaf/papermap#4]
`$ .env/bin/papermap --size A4 wgs84 48 8 out.pdf`

=>

```
Traceback (most recent call last):
  File ".env/bin/papermap", line 8, in <module>
    sys.exit(main())
  File "/fome/flopp/papermap/.env/lib/python3.8/site-packages/papermap/papermap.py", line 535, in main
    pm.render()
  File "/fome/flopp/papermap/.env/lib/python3.8/site-packages/papermap/papermap.py", line 414, in render
    self.render_attribution_and_scale()
  File "/fome/flopp/papermap/.env/lib/python3.8/site-packages/papermap/papermap.py", line 311, in render_attribution_and_scale
    font = ImageFont.truetype('arial.ttf', 35)
  File "/fome/flopp/papermap/.env/lib/python3.8/site-packages/PIL/ImageFont.py", line 836, in truetype
    return freetype(font)
  File "/fome/flopp/papermap/.env/lib/python3.8/site-packages/PIL/ImageFont.py", line 833, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/fome/flopp/papermap/.env/lib/python3.8/site-packages/PIL/ImageFont.py", line 193, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by sgraaf** [comment]
Closed by #5.
